In [2]:
import numpy as np
import LinReg
import random

In [4]:
M=np.loadtxt(open("dataset.txt", "rb"), delimiter=",")

In [5]:
M[0]

array([8.  , 1.  , 0.19, 0.33, 0.02, 0.9 , 0.12, 0.17, 0.34, 0.47, 0.29,
       0.32, 0.2 , 1.  , 0.37, 0.72, 0.34, 0.6 , 0.29, 0.15, 0.43, 0.39,
       0.4 , 0.39, 0.32, 0.27, 0.27, 0.41, 0.08, 0.19, 0.1 , 0.18, 0.48,
       0.27, 0.68, 0.23, 0.41, 0.25, 0.52, 0.68, 0.4 , 0.75, 0.75, 0.35,
       0.55, 0.59, 0.61, 0.56, 0.74, 0.76, 0.04, 0.14, 0.03, 0.24, 0.27,
       0.37, 0.39, 0.07, 0.07, 0.08, 0.08, 0.89, 0.06, 0.14, 0.13, 0.33,
       0.39, 0.28, 0.55, 0.09, 0.51, 0.5 , 0.21, 0.71, 0.52, 0.05, 0.26,
       0.65, 0.14, 0.06, 0.22, 0.19, 0.18, 0.36, 0.35, 0.38, 0.34, 0.38,
       0.46, 0.25, 0.04, 0.  , 0.12, 0.42, 0.5 , 0.51, 0.64, 0.12, 0.26,
       0.2 , 0.32, 0.2 ])

In [6]:
X=M[:,:-1]

In [7]:
Y=M[:,-1]

In [14]:
L=LinReg.LinReg()

In [28]:
L.get_fitness(X, Y)

0.1364191694560535

In [36]:
bitstring=np.ones(101)

In [37]:
L.get_columns(X,bitstring)

array([[8.0e+00, 1.0e+00, 1.9e-01, ..., 2.6e-01, 2.0e-01, 3.2e-01],
       [5.3e+01, 1.0e+00, 0.0e+00, ..., 1.2e-01, 4.5e-01, 0.0e+00],
       [2.4e+01, 1.0e+00, 0.0e+00, ..., 2.1e-01, 2.0e-02, 0.0e+00],
       ...,
       [9.0e+00, 1.0e+01, 1.6e-01, ..., 3.2e-01, 1.8e-01, 9.1e-01],
       [2.5e+01, 1.0e+01, 8.0e-02, ..., 3.8e-01, 3.3e-01, 2.2e-01],
       [6.0e+00, 1.0e+01, 2.0e-01, ..., 3.0e-01, 5.0e-02, 1.0e+00]])

In [38]:
def initiate_population(n):
    return np.random.randint(2, size=(n,101))

In [48]:
I=initiate_population(10)

In [42]:
L.get_columns(X,bitstring)

array([[ 8.,  8.,  8., ...,  8.,  8.,  8.],
       [53., 53., 53., ..., 53., 53., 53.],
       [24., 24., 24., ..., 24., 24., 24.],
       ...,
       [ 9.,  9.,  9., ...,  9.,  9.,  9.],
       [25., 25., 25., ..., 25., 25., 25.],
       [ 6.,  6.,  6., ...,  6.,  6.,  6.]])

In [115]:
def parent_trivial_selection(P,n):
    F=[]
    for i,row in enumerate(P):
        X_filtered=L.get_columns(X,row)
        F.append([i,L.get_fitness(X, Y)])
    F=np.array(F)
    F=F[F[:, 1].argsort()[::-1]]
    F=F[:n,:]
    F=F[:,0]
    F=F.astype(int)
    return P[F].tolist()

In [117]:
p=parent_trivial_selection(I,5)

In [155]:
random.randint(0,1)

1

In [119]:
p[4]

[0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1]

In [158]:
c1=[]
c2=[]
for i in range(len(p1)):
    if random.randint(0,1)==0:
        c1.append(p1[i])
        c2.append(p2[i])
    else:
        c1.append(p2[i])
        c2.append(p1[i])

In [161]:
np.array(c1)

array([0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0])

In [160]:
p1

array([0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0])

In [103]:
c1

[0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 [0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0]]

In [3]:
np.array(np.array([1]))

array([1])